stages:
  - test
  - build
  - deploy

default:
  tags:
    - ci

variables:
  MIN_COVERAGE: 80  # set the threshold at 80%

test project:
  stage: test
  image: node:15
  script:
    - yarn install
    - yarn test
  coverage: '/TOTAL.+ ([0-9]{1,3}%)/'
  cache:
    paths:
      - node_modules/

build project:
  stage: build
  image: node:15
  script:
    - yarn install
    - yarn build
  cache:
    paths:
      - node_modules/
  artifacts:
    expire_in: 1 days
    when: on_success
    paths:
      - build/

netlify:
  stage: deploy
  image: node:15
  script:
    - npm install -g netlify-cli
    - netlify deploy --dir=build --prod
